"""
GitHub PR creation for agent changes.
"""
import subprocess
from pathlib import Path
from typing import Optional
from github import Github, GithubException


class GitHubPRError(Exception):
    """Raised when PR creation fails."""
    pass


class GitHubPRCreator:
    """Creates pull requests on GitHub for agent changes."""

    def __init__(self, token: str, repo_url: str):
        """
        Initialize PR creator.

        Args:
            token: GitHub personal access token
            repo_url: Repository URL (e.g., 'owner/repo' or full URL)
        """
        self.github = Github(token)

        # Parse repo from URL
        if repo_url.startswith('http'):
            # Extract owner/repo from URL
            parts = repo_url.rstrip('/').split('/')
            self.repo_full_name = f"{parts[-2]}/{parts[-1].replace('.git', '')}"
        else:
            self.repo_full_name = repo_url

        try:
            self.repo = self.github.get_repo(self.repo_full_name)
        except GithubException as e:
            raise GitHubPRError(f"Failed to access repository {self.repo_full_name}: {e}")

    def create_pr(
        self,
        worktree_path: str,
        branch_name: str,
        title: str,
        body: str,
        base_branch: str = "main"
    ) -> str:
        """
        Create a pull request from agent changes.

        Args:
            worktree_path: Path to git worktree with changes
            branch_name: Branch name (already created in worktree)
            title: PR title
            body: PR description
            base_branch: Target branch for PR

        Returns:
            str: PR URL

        Raises:
            GitHubPRError: If PR creation fails
        """
        worktree_path = Path(worktree_path)

        try:
            # Stage all changes in worktree
            subprocess.run(
                ["git", "add", "-A"],
                cwd=worktree_path,
                check=True,
                capture_output=True
            )

            # Check if there are changes to commit
            status_result = subprocess.run(
                ["git", "status", "--porcelain"],
                cwd=worktree_path,
                check=True,
                capture_output=True,
                text=True
            )

            if not status_result.stdout.strip():
                raise GitHubPRError("No changes to commit")

            # Commit changes
            commit_message = f"{title}\n\n{body}\n\n🤖 Generated by ob1 orchestrator"
            subprocess.run(
                ["git", "commit", "-m", commit_message],
                cwd=worktree_path,
                check=True,
                capture_output=True,
                text=True
            )

            # Push branch to remote
            subprocess.run(
                ["git", "push", "origin", branch_name],
                cwd=worktree_path,
                check=True,
                capture_output=True,
                text=True
            )

            # Create PR via GitHub API
            pr = self.repo.create_pull(
                title=title,
                body=body,
                head=branch_name,
                base=base_branch
            )

            return pr.html_url

        except subprocess.CalledProcessError as e:
            error_msg = e.stderr.decode() if e.stderr else str(e)
            raise GitHubPRError(f"Git operation failed: {error_msg}")

        except GithubException as e:
            if e.status == 422 and "pull request already exists" in str(e.data).lower():
                # PR already exists, try to find it
                try:
                    pulls = self.repo.get_pulls(
                        state='open',
                        head=f"{self.repo.owner.login}:{branch_name}",
                        base=base_branch
                    )
                    if pulls.totalCount > 0:
                        return pulls[0].html_url
                except:
                    pass

            raise GitHubPRError(f"GitHub API error: {e}")

        except Exception as e:
            raise GitHubPRError(f"Unexpected error: {e}")
